FROM python:3
COPY ./app app/

COPY requirements.txt /tmp/requirements.txt

RUN python3 -m pip install -r /tmp/requirements.txt
RUN cd app
RUN pwd
RUN ls
WORKDIR /app/
RUN ln -fs /usr/share/zoneinfo/America/Belem /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
CMD ["python3","./script.py"]
# RUN python3 ./script.py