version: "3.3"
services:
  api:
    build: ./api_space_flight/
    container_name: api_server_container
    ports:
      - "65511:8080"
  cron_server:
    build: ./cron_db_feed/
    container_name: cron_server_container
